In [2]:
from zipfile import ZipFile
from urllib.request import urlopen   
import pandas as pd
import os

URLs = ['https://s3.amazonaws.com/tripdata/201601-citibike-tripdata.zip',\
       'https://s3.amazonaws.com/tripdata/201602-citibike-tripdata.zip',\
       'https://s3.amazonaws.com/tripdata/201603-citibike-tripdata.zip',\
        'https://s3.amazonaws.com/tripdata/201604-citibike-tripdata.zip',\
        'https://s3.amazonaws.com/tripdata/201605-citibike-tripdata.zip',\
        'https://s3.amazonaws.com/tripdata/201606-citibike-tripdata.zip',\
        'https://s3.amazonaws.com/tripdata/201607-citibike-tripdata.zip',\
        'https://s3.amazonaws.com/tripdata/201608-citibike-tripdata.zip',\
        'https://s3.amazonaws.com/tripdata/201609-citibike-tripdata.zip',\
        'https://s3.amazonaws.com/tripdata/201610-citibike-tripdata.zip',\
        'https://s3.amazonaws.com/tripdata/201611-citibike-tripdata.zip',\
        'https://s3.amazonaws.com/tripdata/201612-citibike-tripdata.zip']
       
dfs=[]
for URL in URLs:
# open and save the zip file onto computer
    url = urlopen(URL)
    output = open('zipFile.zip', 'wb')    # note the flag:  "wb"        
    output.write(url.read())
    output.close()

# read the zip file as a pandas dataframe
    df = pd.read_csv('zipFile.zip')      
    dfs.append(df)
# if keeping on disk the zip file is not wanted, then:
#os.remove(201307-citibike-tripdata.zip)   # remove the copy of the zipfile on disk

In [3]:
dfs[1].head(5)

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,461,2/1/2016 00:00:08,2/1/2016 00:07:49,480,W 53 St & 10 Ave,40.766697,-73.990617,524,W 43 St & 6 Ave,40.755273,-73.983169,23292,Subscriber,1966.0,1
1,297,2/1/2016 00:00:56,2/1/2016 00:05:53,463,9 Ave & W 16 St,40.742065,-74.004432,380,W 4 St & 7 Ave S,40.734011,-74.002939,15329,Subscriber,1977.0,1
2,280,2/1/2016 00:01:00,2/1/2016 00:05:40,3134,3 Ave & E 62 St,40.763126,-73.965269,3141,1 Ave & E 68 St,40.765005,-73.958185,22927,Subscriber,1987.0,1
3,662,2/1/2016 00:01:00,2/1/2016 00:12:02,537,Lexington Ave & E 24 St,40.740259,-73.984092,428,E 3 St & 1 Ave,40.724677,-73.987834,20903,Subscriber,1983.0,2
4,355,2/1/2016 00:01:41,2/1/2016 00:07:36,284,Greenwich Ave & 8 Ave,40.739017,-74.002638,521,8 Ave & W 31 St,40.750967,-73.994442,23228,Subscriber,1978.0,1

In [4]:
dfs[0].head(5)

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,923,1/1/2016 00:00:41,1/1/2016 00:16:04,268,Howard St & Centre St,40.719105,-73.999733,3002,South End Ave & Liberty St,40.711512,-74.015756,22285,Subscriber,1958.0,1
1,379,1/1/2016 00:00:45,1/1/2016 00:07:04,476,E 31 St & 3 Ave,40.743943,-73.979661,498,Broadway & W 32 St,40.748549,-73.988084,17827,Subscriber,1969.0,1
2,589,1/1/2016 00:00:48,1/1/2016 00:10:37,489,10 Ave & W 28 St,40.750664,-74.001768,284,Greenwich Ave & 8 Ave,40.739017,-74.002638,21997,Subscriber,1982.0,2
3,889,1/1/2016 00:01:06,1/1/2016 00:15:56,268,Howard St & Centre St,40.719105,-73.999733,3002,South End Ave & Liberty St,40.711512,-74.015756,22794,Subscriber,1961.0,2
4,1480,1/1/2016 00:01:12,1/1/2016 00:25:52,2006,Central Park S & 6 Ave,40.765909,-73.976342,2006,Central Park S & 6 Ave,40.765909,-73.976342,14562,Subscriber,1952.0,1

In [5]:
dfs[8].head(5)

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,975,9/1/2016 00:00:02,9/1/2016 00:16:18,312,Allen St & Stanton St,40.722055,-73.989111,313,Washington Ave & Park Ave,40.696102,-73.967510,22609,Subscriber,1985.0,1
1,1220,9/1/2016 00:00:04,9/1/2016 00:20:25,316,Fulton St & William St,40.709560,-74.006536,239,Willoughby St & Fleet St,40.691966,-73.981302,16966,Subscriber,1977.0,2
2,308,9/1/2016 00:00:19,9/1/2016 00:05:27,479,9 Ave & W 45 St,40.760193,-73.991255,448,W 37 St & 10 Ave,40.756604,-73.997901,25601,Subscriber,1983.0,1
3,250,9/1/2016 00:00:25,9/1/2016 00:04:35,297,E 15 St & 3 Ave,40.734232,-73.986923,487,E 20 St & FDR Drive,40.733143,-73.975739,22094,Subscriber,1953.0,1
4,439,9/1/2016 00:00:25,9/1/2016 00:07:45,494,W 26 St & 8 Ave,40.747348,-73.997236,533,Broadway & W 39 St,40.752996,-73.987216,16319,Subscriber,1985.0,1

In [6]:
dfs[8].columns

Index(['tripduration', 'starttime', 'stoptime', 'start station id',
       'start station name', 'start station latitude',
       'start station longitude', 'end station id', 'end station name',
       'end station latitude', 'end station longitude', 'bikeid', 'usertype',
       'birth year', 'gender'],
      dtype='object')

In [7]:
dfs[9].head(5)

,Trip Duration,Start Time,Stop Time,Start Station ID,Start Station Name,Start Station Latitude,Start Station Longitude,End Station ID,End Station Name,End Station Latitude,End Station Longitude,Bike ID,User Type,Birth Year,Gender
0,328,2016-10-01 00:00:07,2016-10-01 00:05:35,471,Grand St & Havemeyer St,40.712868,-73.956981,3077,Stagg St & Union Ave,40.708771,-73.950953,25254,Subscriber,1992.0,1
1,398,2016-10-01 00:00:11,2016-10-01 00:06:49,3147,E 85 St & 3 Ave,40.778012,-73.954071,3140,1 Ave & E 78 St,40.771404,-73.953517,17810,Subscriber,1988.0,2
2,430,2016-10-01 00:00:14,2016-10-01 00:07:25,345,W 13 St & 6 Ave,40.736494,-73.997044,470,W 20 St & 8 Ave,40.743453,-74.000040,20940,Subscriber,1965.0,1
3,351,2016-10-01 00:00:21,2016-10-01 00:06:12,3307,West End Ave & W 94 St,40.794165,-73.974124,3357,W 106 St & Amsterdam Ave,40.800836,-73.966449,19086,Subscriber,1993.0,1
4,2693,2016-10-01 00:00:21,2016-10-01 00:45:15,3428,8 Ave & W 16 St,40.740983,-74.001702,3323,W 106 St & Central Park West,40.798186,-73.960591,26502,Subscriber,1991.0,1

In [8]:
dfs[9].columns = ['tripduration', 'starttime', 'stoptime', 'start station id',
       'start station name', 'start station latitude',
       'start station longitude', 'end station id', 'end station name',
       'end station latitude', 'end station longitude', 'bikeid', 'usertype',
       'birth year', 'gender']

In [9]:
dfs[10].columns = ['tripduration', 'starttime', 'stoptime', 'start station id',
       'start station name', 'start station latitude',
       'start station longitude', 'end station id', 'end station name',
       'end station latitude', 'end station longitude', 'bikeid', 'usertype',
       'birth year', 'gender']

In [10]:
dfs[11].columns = ['tripduration', 'starttime', 'stoptime', 'start station id',
       'start station name', 'start station latitude',
       'start station longitude', 'end station id', 'end station name',
       'end station latitude', 'end station longitude', 'bikeid', 'usertype',
       'birth year', 'gender']

In [11]:
dfs[10].head(2)

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,331,2016-11-01 00:00:08,2016-11-01 00:05:40,324,DeKalb Ave & Hudson Ave,40.689888,-73.981013,419,Carlton Ave & Park Ave,40.695807,-73.973556,21959,Subscriber,1981.0,1
1,740,2016-11-01 00:00:08,2016-11-01 00:12:29,161,LaGuardia Pl & W 3 St,40.729170,-73.998102,265,Stanton St & Chrystie St,40.722293,-73.991475,20172,Subscriber,1991.0,1

In [12]:
print('Converting month:')
for month in range(12):
    if month > 8 :
        print('... ' + str(month + 1))
        dfs[month]['starttime'] = pd.to_datetime(dfs[month]['starttime'])
        dfs[month]['stoptime'] = pd.to_datetime(dfs[month]['stoptime'])
        
    else: 
        print('... ' + str(month + 1))
        dfs[month]['starttime'] = pd.to_datetime(dfs[month]['starttime'],
                                                 format = '%m/%d/%Y %H:%M:%S')
        dfs[month]['stoptime'] = pd.to_datetime(dfs[month]['stoptime'],
                                                format = '%m/%d/%Y %H:%M:%S')

Converting month:
... 1
... 2
... 3
... 4
... 5
... 6
... 7
... 8
... 9
... 10
... 11
... 12

In [13]:
dfs[11].head(2)

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,528,2016-12-01 00:00:04,2016-12-01 00:08:52,499,Broadway & W 60 St,40.769155,-73.981918,228,E 48 St & 3 Ave,40.754601,-73.971879,26931,Subscriber,1964.0,1
1,218,2016-12-01 00:00:28,2016-12-01 00:04:06,3418,Plaza St West & Flatbush Ave,40.675021,-73.971115,3358,Garfield Pl & 8 Ave,40.671198,-73.974841,27122,Subscriber,1955.0,1

In [14]:

df = pd.concat(dfs)
df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,923,2016-01-01 00:00:41,2016-01-01 00:16:04,268,Howard St & Centre St,40.719105,-73.999733,3002,South End Ave & Liberty St,40.711512,-74.015756,22285,Subscriber,1958.0,1
1,379,2016-01-01 00:00:45,2016-01-01 00:07:04,476,E 31 St & 3 Ave,40.743943,-73.979661,498,Broadway & W 32 St,40.748549,-73.988084,17827,Subscriber,1969.0,1
2,589,2016-01-01 00:00:48,2016-01-01 00:10:37,489,10 Ave & W 28 St,40.750664,-74.001768,284,Greenwich Ave & 8 Ave,40.739017,-74.002638,21997,Subscriber,1982.0,2
3,889,2016-01-01 00:01:06,2016-01-01 00:15:56,268,Howard St & Centre St,40.719105,-73.999733,3002,South End Ave & Liberty St,40.711512,-74.015756,22794,Subscriber,1961.0,2
4,1480,2016-01-01 00:01:12,2016-01-01 00:25:52,2006,Central Park S & 6 Ave,40.765909,-73.976342,2006,Central Park S & 6 Ave,40.765909,-73.976342,14562,Subscriber,1952.0,1
5,332,2016-01-01 00:01:19,2016-01-01 00:06:51,3104,Kent Ave & N 7 St,40.720577,-73.961502,389,Broadway & Berry St,40.710446,-73.965251,15788,Subscriber,1984.0,1
6,2321,2016-01-01 00:01:27,2016-01-01 00:40:08,3167,Amsterdam Ave & W 73 St,40.779668,-73.980930,3164,Columbus Ave & W 72 St,40.777057,-73.978985,24183,Subscriber,1963.0,1
7,694,2016-01-01 00:02:18,2016-01-01 00:13:53,268,Howard St & Centre St,40.719105,-73.999733,497,E 17 St & Broadway,40.737050,-73.990093,15747,Subscriber,1996.0,1
8,1376,2016-01-01 00:03:12,2016-01-01 00:26:09,527,E 33 St & 2 Ave,40.744023,-73.976056,259,South St & Whitehall St,40.701221,-74.012342,23933,Subscriber,1963.0,1
9,615,2016-01-01 00:03:43,2016-01-01 00:13:59,432,E 7 St & Avenue A,40.726218,-73.983799,311,Norfolk St & Broome St,40.717227,-73.988021,23993,Subscriber,1971.0,1
10,1770,2016-01-01 00:04:43,2016-01-01 00:34:14,3226,W 82 St & Central Park West,40.782750,-73.971370,509,9 Ave & W 22 St,40.745497,-74.001971,22541,Subscriber,1970.0,1
11,525,2016-01-01 00:05:40,2016-01-01 00:14:25,331,Pike St & Monroe St,40.711731,-73.991930,236,St Marks Pl & 2 Ave,40.728419,-73.987140,22193,Subscriber,1988.0,1
12,667,2016-01-01 00:05:41,2016-01-01 00:16:49,444,Broadway & W 24 St,40.742354,-73.989151,490,8 Ave & W 33 St,40.751551,-73.993934,18665,Subscriber,1964.0,1
13,240,2016-01-01 00:06:35,2016-01-01 00:10:36,3165,Central Park West & W 72 St,40.775794,-73.976206,3168,Central Park West & W 85 St,40.784727,-73.969617,22174,Subscriber,1976.0,1
14,539,2016-01-01 00:07:39,2016-01-01 00:16:39,3117,Franklin St & Dupont St,40.735640,-73.958660,3104,Kent Ave & N 7 St,40.720577,-73.961502,15061,Subscriber,1989.0,1
15,1245,2016-01-01 00:08:17,2016-01-01 00:29:03,442,W 27 St & 7 Ave,40.746647,-73.993915,545,E 23 St & 1 Ave,40.736502,-73.978095,24071,Subscriber,1970.0,1
16,479,2016-01-01 00:08:42,2016-01-01 00:16:42,3117,Franklin St & Dupont St,40.735640,-73.958660,3104,Kent Ave & N 7 St,40.720577,-73.961502,23563,Subscriber,1993.0,1
17,888,2016-01-01 00:08:47,2016-01-01 00:23:36,284,Greenwich Ave & 8 Ave,40.739017,-74.002638,439,E 4 St & 2 Ave,40.726281,-73.989780,15082,Subscriber,1982.0,1
18,398,2016-01-01 00:09:19,2016-01-01 00:15:58,483,E 12 St & 3 Ave,40.732233,-73.988900,483,E 12 St & 3 Ave,40.732233,-73.988900,15721,Subscriber,1972.0,2
19,858,2016-01-01 00:09:31,2016-01-01 00:23:49,532,S 5 Pl & S 4 St,40.710451,-73.960876,401,Allen St & Rivington St,40.720196,-73.989978,17057,Customer,NaN,0
20,839,2016-01-01 00:09:55,2016-01-01 00:23:54,532,S 5 Pl & S 4 St,40.710451,-73.960876,401,Allen St & Rivington St,40.720196,-73.989978,17109,Customer,NaN,0
21,719,2016-01-01 00:10:00,2016-01-01 00:21:59,3116,Huron St & Franklin St,40.732660,-73.958260,3126,44 Dr & Jackson Ave,40.747182,-73.943264,16624,Subscriber,1982.0,1
22,110,2016-01-01 00:10:24,2016-01-01 00:12:15,439,E 4 St & 2 Ave,40.726281,-73.989780,439,E 4 St & 2 Ave,40.726281,-73.989780,24021,Customer,NaN,0
23,280,2016-01-01 00:10:29,2016-01-01 00:15:09,512,W 29 St & 9 Ave,40.750073,-73.998393,466,W 25 St & 6 Ave,40.743954,-73.991449,23144,Subscriber,1988.0,1
24,937,2016-01-01 00:10:45,2016-01-01 00:26:22,387,Centre St & Chambers St,40.712733,-74.004607,503,E 20 St & Park Ave,40.738274,-73.987520,23650,Subscriber,1982.0,2
25,2038,2016-01-01 00:10:50,2016-01-01 00:44:49,3143,5 Ave & E 78 St,40.776829,-73.963888,479,9 Ave & W 45 St,40.760193,-73.991255,19804,Subscriber,1963.0,2
26,2023,2016-01-01 00:11:15,2016-01-01 00:44:58,3143,5 Ave & E 78 St,40.776829,-73.963888,479,9 Ave & W 45 St,40.760193,-73.991255,14769,Customer,NaN,0
27,743,2016-01-01 00:11:42,2016-01-01 00:24:05,531,Forsyth St & Broome St,40.718939,-73.992663,2003,1 Ave & E 18 St,40.733812,-73.980544,21624,Subscriber,1970.0,2
28,1236,2016-01-01 00:12:14,2016-01-01 00:32:50,3231,E 67 St & Park Ave,40.767801,-73.965921,3231,E 67 St & Park Ave,40.767801,-73.965921,16475,Customer,NaN,0
29,662,2016-01-01 00:12:16,2016-01-01 00:23:19,3175,W 70 St & Amsterdam Ave,40.777480,-73.982886,3166,Riverside Dr & W 72 St,40.780578,-73.985624,22560,Subscriber,1976.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
812162,1534,2016-12-31 23:45:48,2017-01-01 00:11:22,3372,E 74 St & 1 Ave,40.768974,-73.954823,505,6 Ave & W 33 St,40.749013,-73.988484,25231,Subscriber,1962.0,1
812163,870,2016-12-31 23:46:35,2017-01-01 00:01:05,383,Greenwich Ave & Charles St,40.735238,-74.000271,383,Greenwich Ave & Charles St,40.735238,-74.000271,26764,Subscriber,1987.0,1
812164,191,2016-12-31 23:46:46,2016-12-31 23:49:58,3241,Monroe St & Tompkins Ave,40.686203,-73.944694,344,Monroe St & Bedford Ave,40.685144,-73.953809,19072,Subscriber,1984.0,1
812165,519,2016-12-31 23:46:50,2016-12-31 23:55:29,438,St Marks Pl & 1 Ave,40.727791,-73.985649,247,Perry St & Bleecker St,40.735354,-74.004831,24936,Subscriber,1962.0,1
812166,549722,2016-12-31 23:47:26,2017-01-07 08:29:28,322,Clinton St & Tillary St,40.696192,-73.991218,3411,Bond St & Bergen St,40.684967,-73.986208,14545,Subscriber,NaN,0
812167,346,2016-12-31 23:47:26,2016-12-31 23:53:12,322,Clinton St & Tillary St,40.696192,-73.991218,3411,Bond St & Bergen St,40.684967,-73.986208,16692,Subscriber,NaN,0
812168,197,2016-12-31 23:47:30,2016-12-31 23:50:48,3113,Greenpoint Ave & Manhattan Ave,40.730260,-73.953940,3117,Franklin St & Dupont St,40.735640,-73.958660,26972,Subscriber,1988.0,1
812169,1806,2016-12-31 23:48:29,2017-01-01 00:18:35,3311,Columbia St & Kane St,40.687632,-74.001626,3311,Columbia St & Kane St,40.687632,-74.001626,16738,Customer,NaN,0
812170,1768,2016-12-31 23:48:51,2017-01-01 00:18:20,2008,Little West St & 1 Pl,40.705693,-74.016777,2008,Little West St & 1 Pl,40.705693,-74.016777,16818,Customer,NaN,0
812171,1855,2016-12-31 23:48:49,2017-01-01 00:19:45,2008,Little West St & 1 Pl,40.705693,-74.016777,2008,Little West St & 1 Pl,40.705693,-74.016777,21258,Subscriber,1992.0,2
812172,419,2016-12-31 23:48:58,2016-12-31 23:55:57,491,E 24 St & Park Ave S,40.740964,-73.986022,236,St Marks Pl & 2 Ave,40.728419,-73.987140,14929,Subscriber,1992.0,1
812173,781,2016-12-31 23:49:22,2017-01-01 00:02:24,368,Carmine St & 6 Ave,40.730386,-74.002150,488,W 39 St & 9 Ave,40.756458,-73.993722,27178,Subscriber,1968.0,1
812174,88,2016-12-31 23:49:42,2016-12-31 23:51:10,3146,E 81 St & 3 Ave,40.775730,-73.956753,3147,E 85 St & 3 Ave,40.778012,-73.954071,27134,Subscriber,1974.0,1
812175,227,2016-12-31 23:50:23,2016-12-31 23:54:11,499,Broadway & W 60 St,40.769155,-73.981918,3164,Columbus Ave & W 72 St,40.777057,-73.978985,25196,Subscriber,1985.0,1
812176,1473,2016-12-31 23:50:39,2017-01-01 00:15:13,3134,3 Ave & E 62 St,40.763126,-73.965269,345,W 13 St & 6 Ave,40.736494,-73.997044,20153,Subscriber,1953.0,1
812177,316,2016-12-31 23:51:27,2016-12-31 23:56:43,161,LaGuardia Pl & W 3 St,40.729170,-73.998102,438,St Marks Pl & 1 Ave,40.727791,-73.985649,26790,Subscriber,1958.0,1
812178,983,2016-12-31 23:51:29,2017-01-01 00:07:53,513,W 56 St & 10 Ave,40.768254,-73.988639,509,9 Ave & W 22 St,40.745497,-74.001971,17504,Subscriber,NaN,0
812179,275,2016-12-31 23:51:55,2016-12-31 23:56:31,539,Metropolitan Ave & Bedford Ave,40.715348,-73.960241,3091,Frost St & Meeker St,40.717640,-73.948820,24819,Subscriber,1991.0,2
812180,2182,2016-12-31 23:52:04,2017-01-01 00:28:26,3360,Amsterdam Ave & W 79 St,40.782939,-73.978652,3162,W 78 St & Broadway,40.783400,-73.980931,26842,Subscriber,1975.0,2
812181,128,2016-12-31 23:52:34,2016-12-31 23:54:42,3438,E 76 St & 3 Ave,40.772249,-73.958421,3372,E 74 St & 1 Ave,40.768974,-73.954823,23151,Subscriber,1965.0,1
812182,1126,2016-12-31 23:52:54,2017-01-01 00:11:41,312,Allen St & Stanton St,40.722055,-73.989111,312,Allen St & Stanton St,40.722055,-73.989111,23952,Subscriber,1997.0,1
812183,1089,2016-12-31 23:53:23,2017-01-01 00:11:33,3171,Amsterdam Ave & W 82 St,40.785247,-73.976673,3165,Central Park West & W 72 St,40.775794,-73.976206,16115,Subscriber,1969.0,1
812184,750,2016-12-31 23:53:28,2017-01-01 00:05:58,3113,Greenpoint Ave & Manhattan Ave,40.730260,-73.953940,3093,N 6 St & Bedford Ave,40.717452,-73.958509,24939,Subscriber,1983.0,1
812185,1258,2016-12-31 23:53:42,2017-01-01 00:14:41,334,W 20 St & 7 Ave,40.742388,-73.997262,488,W 39 St & 9 Ave,40.756458,-73.993722,26811,Subscriber,1988.0,1
812186,121,2016-12-31 23:55:50,2016-12-31 23:57:52,3236,W 42 St & Dyer Ave,40.758985,-73.993800,478,11 Ave & W 41 St,40.760301,-73.998842,25923,Subscriber,1987.0,1
812187,441,2016-12-31 23:56:15,2017-01-01 00:03:36,284,Greenwich Ave & 8 Ave,40.739017,-74.002638,336,Sullivan St & Washington Sq,40.730477,-73.999061,16185,Subscriber,1974.0,2
812188,1026,2016-12-31 23:56:19,2017-01-01 00:13:26,281,Grand Army Plaza & Central Park S,40.764397,-73.973715,3143,5 Ave & E 78 St,40.776829,-73.963888,18267,NaN,1983.0,1
812189,1747,2016-12-31 23:56:35,2017-01-01 00:25:43,3424,E 106 St & Lexington Ave,40.791976,-73.945993,3295,Central Park W & W 96 St,40.791270,-73.964839,19899,Subscriber,1970.0,2
812190,951,2016-12-31 23:59:31,2017-01-01 00:15:23,3158,W 63 St & Broadway,40.771639,-73.982614,3169,Riverside Dr & W 82 St,40.787209,-73.981281,16866,Subscriber,1961.0,1
812191,1322,2016-12-31 23:59:56,2017-01-01 00:21:58,3263,Cooper Square & E 7 St,40.729236,-73.990868,498,Broadway & W 32 St,40.748549,-73.988084,25793,Subscriber,1985.0,1

In [ ]:
df.shape

(13845655, 15)

In [ ]:
df.to_csv('Data/citibike_2016.csv', encoding='utf-8', index=False)